### ISSUE TITLE
Some of my did and cid end up wth"" and this messes things up. 

### ISSUE THREAD

**Issue by Enforcer84** [SirLameGame/bbgm-kit#1]
[roster.txt](https://github.com/SirLameGame/bbgm-kit/files/1257816/roster.txt)

This is the roster file I got when I transferred.  I just changed it to a json file and it works but my conferences were off with empty teams. 

First part was my fault. Fixed that then realized the "" issue.

**Comment by SirLameGame** [comment]
Thanks, bro. It looks like I need to add a check in [here](https://github.com/SirLameGame/bbgm-kit/blob/master/src/components/Home/Teams/reducers/index.js#L29) that makes sure to force some of the team attributes as integers or rounded floats in some cases. Hopefully, will push a fix this week.
